# Generated by Django 5.2.11 on 2026-04-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_taskcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deadline_reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
