# Generated by Django 5.2.11 on 2026-04-30 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
